/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import java.sql.Connection;
import model.Project;
import util.ConnectionFactory;

public class App {

    public static void main(String[] args) {
        
//        Connection c = ConnectionFactory.getConnection();
//        System.out.println(c);
//        
//        ConnectionFactory.closeConnection(c);

        Project project = new Project();
        project.setName("Teste1");
        project.setDescription("Teste 1 desc");
        
        ProjectController controller = new ProjectController();
        controller.save(project);

    }
}
